site_name: Documentation for Labii.com

pages:
- [index.md, Home]
- [profiles.md, Academic profiles]
- [groups.md, Research groups]
- [references.md, Reference Manager]
- [bmc.md, BMC]

theme_dir: 'bootstrap_labii'

copyright: 'LabII LLC ©2014-2015'

site_description: "Labii is a professional network for academics. We provide multiple services including: 1) Academic Profiles for individual scientist to document his/her academic activities; 2) Research Groups for a group of scientists to manage and broadcast their research projects. They could be the scientists from one same laboratory, or same department; or scientists from different labs cooperating in one same project; or even student associations or a company. 3) Reference Manager to provide a post-publication review and rating platform for the scientists to select the most valuable papers to read. 4) Electronic Laboratory Notebook, for fast and accurate lab notes and reports. "

site_author: "LabII support team"

site_favicon: 'favicon.png'

google_analytics: ['UA-39576419-1', 'www.labii.com']

markdown_extensions: [markdown.extensions.smarty, markdown.extensions.extra, markdown.extensions.toc]

repo_url: https://github.com/Labii/labii-docs